# Generated by Django 4.2.7 on 2024-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="modelsform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=100)),
                ("type_de_vehicule", models.CharField(max_length=100)),
                ("climat", models.CharField(max_length=100)),
                ("condition_economique", models.CharField(max_length=100)),
                ("jour", models.CharField(max_length=100)),
                ("heure", models.CharField(max_length=100)),
                ("vitesse", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "consommation_energetique",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("heure_de_pointe", models.BooleanField(default=False)),
                ("evenement_aleatoire", models.BooleanField(default=False)),
            ],
        ),
    ]
