# Generated by Django 4.2.7 on 2024-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelsform",
            name="consommation_energetique",
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name="modelsform",
            name="vitesse",
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
