# Generated by Django 4.2.7 on 2024-05-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_alter_modelsform_consommation_energetique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc", models.FileField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="modelsform",
            name="consommation_energetique",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="modelsform",
            name="vitesse",
            field=models.FloatField(),
        ),
    ]
