# Generated by Django 4.2.7 on 2024-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_doc_alter_modelsform_consommation_energetique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="linkdin",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="doc",
            name="portfolio",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
